[package]
name = "follow-frameworks"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "Produces Temporally-Animated Volumetric Renders of Cosmological Spacetime from AdvancedLIGO and JWST Datasets."
repository = "https://github.com/EraExa/Follow"
authors = ["Axel Selmer-Anderssen <era.exa@outlook.com>"]
